#!/bin/bash
CONTAINER=$1
REMOTE=$2
DATABASE=$3
TABLE=$4
KEEP_FILE=$5
set -e
set -o pipefail

if [[ -n $CONTAINER ]] && [[ -n $REMOTE ]] && [[ -n $DATABASE ]] && [[ -n $TABLE ]]; then
  set -x
  TS=`date +%Y%m%d%H%M%S`
  FILE=${TABLE}-${TS}.txt
  BACKUP=${TABLE}_${TS}
  echo "\\copy $TABLE to '$FILE'" | heroku pg:psql $DATABASE --remote $REMOTE
  echo "CREATE TABLE $BACKUP ( LIKE $TABLE INCLUDING ALL ) ; INSERT INTO $BACKUP SELECT * FROM $TABLE ; TRUNCATE TABLE $TABLE; \\copy $TABLE from '$FILE'; SELECT setval('${TABLE}_id_seq', GREATEST(1000000000, (SELECT MAX(id) FROM $TABLE), (SELECT MAX(id) FROM $BACKUP)))" | docker exec -i $CONTAINER rails db -p
  if [[ -z $KEEP_FILE ]]; then
    rm $FILE
  fi
else
  echo "Usage: `basename $0` <rails-docker-container> <heroku-remote> <heroku-database> <table> <keep-file-flag>"
  exit 1
fi
