#!/bin/bash
CONTAINER=$1
TABLE=$2
REMOTE=${3:-live}
KEEP_FILE=$4
set -e
set -o pipefail

if [[ -n $CONTAINER ]] && [[ -n $TABLE ]]; then
  set -x
  TS=`date +%Y%m%d%H%M%S`
  FILE=${TABLE}-${TS}.txt
  BACKUP=${TABLE}_${TS}
  echo "\\copy $TABLE to '$FILE'" | heroku pg:psql --remote $REMOTE
  echo "CREATE TABLE $BACKUP ( LIKE $TABLE INCLUDING ALL ) ; INSERT INTO $BACKUP SELECT * FROM $TABLE ; TRUNCATE TABLE $TABLE; \\copy $TABLE from '$FILE'; SELECT setval('${TABLE}_id_seq', max(id)) FROM $TABLE" | docker exec -i $CONTAINER rails db -p
  if [[ -z $KEEP_FILE ]]; then
    rm $FILE
  fi
else
  echo "Usage: `basename $0` <rails-docker-container> <table> <heroku-remote> <keep-file-flag>"
  exit 1
fi
