#!/usr/bin/env bash

# Remove this location from the PATH.

SELFNAME="${0##*/}"
OLD_IFS="$IFS"
OLD_PATH="$PATH"
IFS=":"

NEW_PATH=""
for path in $OLD_PATH; do
  testpath="${path}/${SELFNAME}"
  if ! [ -x "$testpath" ] || [ `diff $0 "$testpath"` ]; then
    NEW_PATH="${NEW_PATH}:${path}"
  fi
done
NEW_PATH="${NEW_PATH#:}"
IFS="$OLD_IFS"

PATH="$NEW_PATH"

[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh # This loads NVM

if type nvm > /dev/null && nvm which > /dev/null 2>&1; then
  nvm use > /dev/null
#else
#  echo "No node version specified by nvm. Using $NODE."
fi

exec "$SELFNAME" "$@"


#set -e
#[ -n "$RBENV_DEBUG" ] && set -x
#
#program="${0##*/}"
#if [ "$program" = "ruby" ]; then
#  for arg; do
#    case "$arg" in
#    -e* | -- ) break ;;
#    */* )
#      if [ -f "$arg" ]; then
#        export RBENV_DIR="${arg%/*}"
#        break
#      fi
#      ;;
#    esac
#  done
#fi
#
#export RBENV_ROOT="/home/steven/.rbenv"
#exec "/home/steven/.rbenv/libexec/rbenv" exec "$program" "$@"
